parameters:
  tests: []

jobs:
- ${{ each test in parameters.tests }}:
  - job: ${{ test }}
    timeoutInMinutes: 90
    cancelTimeoutInMinutes: 90
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform 1.3.4'
      inputs:
        terraformVersion: '1.3.4'

    - bash: |
        cd test
        ./gradlew clean test --tests terraform.azurerm.module.aks.test.${{ test }} --console=plain
      displayName: "Run tests"
      condition: not(failed())
      env:
        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        ARM_TENANT_ID: $(AZURE_TENANT_ID)
        AZURE_ARTIFACTS_ENV_ACCESS_TOKEN: $(PAT)

    - task: PublishTestResults@2
      condition: always()