name: "Create Resource Group"

on:
  workflow_call:
    inputs:
      param_env:
        required: true
        type: string
      param_runner:
        required: true
        type: string
      param_resource_group_name:
        required: true
        type: string
      param_resource_group_location:
        required: true
        type: string
    outputs:
      azure-resource-group-result:
        description: "Azure Resource Group Result"
        value: ${{ jobs.step-id-create-azure-rg.outputs.create-rg-result-output }}

env:
  RESOURCE_GROUP_NAME: ${{ inputs.param_resource_group_name}}
  RESOURCE_GROUP_LOCATION: ${{ inputs.param_resource_group_location}}

jobs:
  create-azure-resource-group:
    name: Create Azure Resource Group
    runs-on: ${{ inputs.param_runner }}
    environment: ${{ inputs.param_env }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    outputs:
      create-rg-result-output: ${{ steps.step-id-create-azure-rg.outputs.step-output-rg-result }}

    steps:

      - name: Create Azure Resource Group
        id: step-id-create-azure-rg
        uses: azure/cli@v2
        with:
          inlineScript: |
            az version

            # Create resource group
            if [ $(az group exists --name $RESOURCE_GROUP_NAME) = false ]; then
              az group create --name $RESOURCE_GROUP_NAME --location $RESOURCE_GROUP_LOCATION
              echo "step-output-rg-result = $RESOURCE_GROUP_NAME Created Successfully!"
            else
              echo "step-output-rg-result = $RESOURCE_GROUP_NAME already exist!"
            fi