name: 'Create Infra with Terraform'

on:
 push:
   branches: [main]
   paths: ./.github/workflows/devops.yml
 workflow_dispatch:

env:
  ENV_STORAGE_ACCOUNT_NAME: storagetfstatelearning
  ENV_STORAGE_ACCOUNT_LOCATION: southeastasia

  ENV_RESOURCE_GROUP_NAME: rg-tf-state-learning
  ENV_RESOURCE_GROUP_LOCATION: southeastasia

  ENV_CONTAINER_NAME: tfstatelearning
  ENV_BLOB_NAME: tflearning.tfstate

jobs:

  # Run unit test to check terraform environment
  #tf-unit-tests:
  #  uses: ./.github/workflows/tf-unit-tests.yml

  login-azure-test:
    name: Login Azure Test
    runs-on: ubuntu-latest

    defaults:
      run:
       shell: bash

    steps:
    # Login to Azure with Service Principal
    - name: Login to Azure with Service Principal
      uses: Azure/login@v2
      with:
        creds: ${{ secrets.AZURE_LEARNING_CREDENTIALS }}
    - run: echo '${{ secrets.AZURE_LEARNING_CREDENTIALS }}'

  deploy-azure-infra-terraform:
    uses: ./.github/workflows/tf-remote-state-ini.yml
    with:
      param_env: development
      param_runner: ubuntu-latest
      param_resource_group_name: $ENV_RESOURCE_GROUP_NAME
      param_resource_group_location: $ENV_RESOURCE_GROUP_LOCATION
    secrets:
      param_azure_credentials: ${{ secrets.AZURE_LEARNING_CREDENTIALS }}