name: "Terraform Initial"

on:
  workflow_call:
    inputs:
      param_env:
        required: true
        type: string
      param_runner:
        required: true
        type: string
      param_resource_group_name:
        required: true
        type: string
      param_resource_group_location:
        required: true
        type: string
    secrets:
      param_azure_credentials:
        required: true

jobs:
  # Create Terraform Backend State Storage
  create-tf-backend-state-storage:
    name: Create Terraform backend state storage
    uses: ./.github/workflows/azure-cli-create-rg.yml
    with:
      env: ${{ inputs.param_env }}
      runner: ${{ inputs.param_runner }}
      resource_group_name: ${{ inputs.param_resource_group_name }}
      resource_group_location: ${{ inputs.param_resource_group_location }}

